name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@5a3fa01c67e60dba8f95e2878436c7151c4b5f01
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  publish-docker:
    runs-on: ubuntu-22.04
    environment: release
    outputs:
      data-aggregator-tag: ${{ steps.setup_tags.outputs.data-aggregator-tag}}
      gateway-api-tag: ${{ steps.setup_tags.outputs.gateway-api-tag}}
    permissions:
      id-token: write
      contents: read
      pull-requests: read 
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0

      - id: auth
        uses: google-github-actions/auth@a61909d048e0be579b6c15b27088d19668493851
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: configure-docker
        run: |
            gcloud auth configure-docker -q

      - name: Setup tags for docker image
        id: setup_tags
        uses: ./.github/actions/set-variables
        with:
          github_event_name: ${{ github.event_name }}
          github_action_name: ${{ github.event.action}}

      - name: Docker build and push DataAggregator
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: ./src/DataAggregator/Dockerfile
          TAGS: |
            ${{ steps.setup_tags.outputs.data_aggregator_tags }}
          push: true
          context: ./

      - name: Docker build and push Gateway API
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: ./src/GatewayAPI/Dockerfile
          TAGS: |
            ${{ steps.setup_tags.outputs.gateway_api_tags }}
          push: true
          context: ./

  deploy-on-sandpitnet:
    runs-on: ubuntu-22.04
    needs: publish-docker
    steps:
      - name: Trigger deployment event ${{ github.ref }}
        env:
          NAMESPACE: "sandpitnet"
          EVENT_TYPE: "ng_dev"
        run: |
          curl --silent --show-error --fail --location --request POST 'https://github-worker.radixdlt.com/repos/radixdlt/${{secrets.DISPATCH_REPO}}/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Basic ${{secrets.CF_GITHUB_WORKER_ENCODED_BASIC_AUTH}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "event_type": "${{env.EVENT_TYPE}}",
                "client_payload": {
                    "namespace_postfix": "${{env.NAMESPACE}}",
                    "data_aggregator_image_tag": "${{ needs.publish-docker.outputs.data-aggregator-tag }}",
                    "gateway_api_image_tag": "${{ needs.publish-docker.outputs.gateway-api-tag }}"
                }
            }'

