name: Gateway API Contract Tests

on:
  pull_request:

jobs:
  build:
    name: Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  dispatch-contract-tests-event:
    runs-on: ubuntu-latest
    steps:
      - name: get ephemeral deployment url
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "EPHEMERAL_URL=https://$pull_number-gateway.radixdlt.com" >> $GITHUB_ENV
          echo "EVENT_TYPE=contract_tests" >> $GITHUB_ENV

      - name: Trigger pull request deployment event ${{ github.ref }}
        run: |
          curl --silent --show-error --fail --location --request POST 'https://github-worker.radixdlt.com/repos/radixdlt/radixdlt-python-clients/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Basic ${{secrets.CF_GITHUB_WORKER_ENCODED_BASIC_AUTH}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "event_type": "${{env.EVENT_TYPE}}",
                "client_payload": {
                    "ephemeral_url": "${{env.EPHEMERAL_URL}}"
                }
            }'
