name: build-publish-dotnet-binary
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: RDXWorks-actions/setup-dotnet@main
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - name: Build linux binaries
        run: |
          cd src/DataAggregator
          dotnet publish --runtime linux-x64 --configuration Release --self-contained false -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false --output ./output
          cd ../GatewayAPI
          dotnet publish --runtime linux-x64 --configuration Release --self-contained false -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false --output ./output
          cd ../..

          zip -r data-aggregator.zip src/DataAggregator/output/
          zip -r gateway-api.zip src/GatewayAPI/output/
      - name: Get release
        id: get_release
        uses: RDXWorks-actions/get-release@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload DataAggreagtor zip
        uses: RDXWorks-actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./data-aggregator.zip
          asset_name: data-aggregator-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload GatewayAPI zip
        uses: RDXWorks-actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./gateway-api.zip
          asset_name: gateway-api-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

